// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_W8dVTZ_0gPONHLh_sUmokRypo-dmLmo',
    appId: '1:416151661037:web:f441b838455d4854da1fe4',
    messagingSenderId: '416151661037',
    projectId: 'suleymankiskacproject',
    authDomain: 'suleymankiskacproject.firebaseapp.com',
    storageBucket: 'suleymankiskacproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyp_aM7IHrMacV6mUvonWy44rZW85z058',
    appId: '1:416151661037:android:286ebd14aceb4a19da1fe4',
    messagingSenderId: '416151661037',
    projectId: 'suleymankiskacproject',
    storageBucket: 'suleymankiskacproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWI7cP4xnVT4rRB0L6e5p2gs0AjSAOCQ',
    appId: '1:416151661037:ios:488ad16981ab67ffda1fe4',
    messagingSenderId: '416151661037',
    projectId: 'suleymankiskacproject',
    storageBucket: 'suleymankiskacproject.appspot.com',
    iosClientId: '416151661037-c06uo4ap71fa1rcgf4f9l2g17q65mbda.apps.googleusercontent.com',
    iosBundleId: 'com.example.suleymankiskacproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWI7cP4xnVT4rRB0L6e5p2gs0AjSAOCQ',
    appId: '1:416151661037:ios:33fc652a4ed65ac0da1fe4',
    messagingSenderId: '416151661037',
    projectId: 'suleymankiskacproject',
    storageBucket: 'suleymankiskacproject.appspot.com',
    iosClientId: '416151661037-mlq9um22apqpgpgarb07brj3up5r6a7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.suleymankiskacproject.RunnerTests',
  );
}
